### ISSUE TITLE
Failed to activate the punchclock package

### ISSUE THREAD

**Issue by robhicks** [queenp/punchclock#2] opened 2015-06-18 12:40 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.210.0
**System**: Mac OS X 10.10.3
**Thrown From**: [punchclock](https://github.com/queenp/punchclock) package, v0.5.0

### Stack Trace

Failed to activate the punchclock package

```
At undefined is not a function

TypeError: undefined is not a function
    at Timer.module.exports.Timer.getPath (/Users/robhicks/.atom/packages/punchclock/lib/timer.coffee:330:35)
    at Timer.module.exports.Timer.save (/Users/robhicks/.atom/packages/punchclock/lib/timer.coffee:273:28)
    at new Timer (/Users/robhicks/.atom/packages/punchclock/lib/timer.coffee:48:16)
    at Object.module.exports.activate (/Users/robhicks/.atom/packages/punchclock/lib/punchclock.coffee:48:22)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:221:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:165:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:213:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:452:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:436:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "autocomplete",
      "file-type-icons",
      "turbo-javascript",
      "last-cursor-position",
      "tabs-to-spaces"
    ],
    "followSymlinks": false,
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
Stylus, v1.0.0
Sublime-Style-Column-Selection, v1.3.0
auto-detect-indentation, v0.4.2
autocomplete-paths, v1.0.2
browser-plus, v0.0.23
file-icons, v1.5.7
filesize, v0.2.0
hide-files, v0.1.7
highlight-line, v0.11.0
highlight-selected, v0.10.1
language-ejs, v0.1.0
linter, v0.12.7
linter-jshint, v0.1.6
linter-stylint, v0.6.0
local-history, v3.2.3
monokai, v0.14.0
navigate, v0.1.6
package-cop, v0.2.10
punchclock, v0.5.0
svg-preview, v0.6.0
tool-bar, v0.1.7

# Dev
No dev packages
```

**Comment by queenp** [comment] 2015-07-20 22:46
Sorry for what a ridiculously long time I've left this. The issue is that I hadn't set an upper bound on the version compatibility of atom for my update fork, and the API changed a few months back during an update. Just getting around to upgrading to the new api now.

**Comment by queenp** [comment] 2015-07-22 16:19
I believe this should be fixed in the latest patch. Please check.

**Closed** 2015-07-22 16:22 UTC
